### ISSUE TITLE
Dedietrich integration

### ISSUE THREAD

**Issue by pawelhulek** [jurgenheine/com.bdr#1]
Hi,
Would you mind adding dedietrich integration?

**Comment by jurgenheine** [comment]
It's possible to add De Dietrich Smart TC If I know the API endpoint of De Dietrich. For now I only know the Baxi and Remeha endpoints. 

Maybe you can help to by trying to find the endpoint. The endpoint url is: https://remoteapp.bdrthermea.com/user/{brand}/login
The {brand} part is unknown for De Dietrich. Unfortunality, I can't try this myself. If it's not correct, always a 401 Unauthorized is returned, only with correct credentials, brand and correct endpoint a 200 OK code is returned. I have only a Remaha account and Baxi code was inital source of code. If you could find the right enpoint, please post it here and I can add the thermostat

Endpoint Remeha:
https://remoteapp.bdrthermea.com/user/remeha/login
Endpoint Baxi:
https://remoteapp.bdrthermea.com/user/baxi/login

### You can test and try with postman.
**URL:** 
POST  `https://remoteapp.bdrthermea.com/user/{brand}/login`
Try here first dedietrich or de_dietrich etc
**Headers:**
```
Accept:application/json,text/plain,*/*
Connection:keep-alive
X-Requested-With:com.bdrthermea.roomunitapplication.baxi
Content-Type:application/json;charset=UTF-8
Sec-Fetch-Site:cross-site
Sec-Fetch-Mode:cors
Sec-Fetch-Dest:empty
Accept-Encoding:gzip,deflate
Authorization:Basic cnVhcHA6V25AW1tjJF1QfjghM2AoW35BZiUnSDI/bEh3XWNpaXE6cn1MT3pqTGsueTVNSCtfcT0=
```
**Body:**
```
{
            "username": "your username",
            "password": "your password"
}
```
![image](https://user-images.githubusercontent.com/17513366/186936727-659e7a09-182d-42a3-b22f-b9f16a43acbd.png)
![image](https://user-images.githubusercontent.com/17513366/186936844-d468bcd6-18c5-4215-b8ed-b58f6c3185a4.png)

**Comment by pawelhulek** [comment]
https://remoteapp.bdrthermea.com/user/dedietrich/login endpoint works ;)

**Comment by jurgenheine** [comment]
Thanks for trying to find the code, I can and will now add De Dietrich Smart TC to the app. I will notify when it become available in test version

**Comment by jurgenheine** [comment]
De thermostat is added to test release: https://homey.app/nl-nl/app/com.bdrthermea/BDR-Thermea-climate/test/
